#!/bin/bash

BASE_DIR=$( cd "$( dirname "$BASH_SOURCE[0]" )" && pwd )
BUNDLED_DIR="$BASE_DIR/teamvault/static/bundled"

rm -rf $BUNDLED_DIR/*

cd $BUNDLED_DIR

ffsjs jquery
ffsjs semantic-ui
ffsjs zxcvbn
