# Generated by Django 4.2.3 on 2023-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_logentry_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="category",
            field=models.CharField(
                choices=[
                    ("secret_read", "secret_read"),
                    (
                        "secret_elevated_superuser_read",
                        "secret_elevated_superuser_read",
                    ),
                    ("secret_permission_violation", "secret_permission_violation"),
                    ("secret_changed", "secret_changed"),
                    (
                        "secret_needs_changing_reminder",
                        "secret_needs_changing_reminder",
                    ),
                    ("secret_shared", "secret_shared"),
                    ("secret_superuser_shared", "secret_superuser_shared"),
                    ("secret_legacy_access_requests", "secret_legacy_access_requests"),
                    ("user_activated", "user_activated"),
                    ("user_deactivated", "user_deactivated"),
                    ("user_settings_changed", "user_settings_changed"),
                    ("miscellaneous", "miscellaneous"),
                ],
                default="miscellaneous",
                max_length=64,
            ),
        ),
    ]
