# Generated by Django 5.2.1 on 2025-09-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_logentry_logentry_category_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('secret_read', 'secret_read'), ('secret_elevated_superuser_read', 'secret_elevated_superuser_read'), ('secret_permission_violation', 'secret_permission_violation'), ('secret_changed', 'secret_changed'), ('secret_needs_changing_reminder', 'secret_needs_changing_reminder'), ('secret_shared', 'secret_shared'), ('secret_superuser_shared', 'secret_superuser_shared'), ('secret_share_removed', 'secret_share_removed'), ('secret_superuser_share_removed', 'secret_superuser_share_removed'), ('secret_legacy_access_requests', 'secret_legacy_access_requests'), ('user_activated', 'user_activated'), ('user_deactivated', 'user_deactivated'), ('user_settings_changed', 'user_settings_changed'), ('share_automatically_revoked', 'share_automatically_revoked'), ('miscellaneous', 'miscellaneous'), ('data_export', 'data_export')], default='miscellaneous', max_length=64),
        ),
    ]
