# Generated by Django 5.2.1 on 2025-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_logentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
