# Generated by Django 6.1 on 2026-09-17 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0010_alter_logentry_category"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("secrets", "0041_fix_passwords_old_payload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logentry",
            name="logentry_actor_idx",
        ),
        migrations.RemoveIndex(
            model_name="logentry",
            name="logentry_group_idx",
        ),
        migrations.RemoveIndex(
            model_name="logentry",
            name="logentry_secret_idx",
        ),
        migrations.RemoveIndex(
            model_name="logentry",
            name="logentry_user_idx",
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(
                fields=["actor", "-time", "secret"],
                name="logentry_actor_time_secret_idx",
            ),
        ),
    ]
