from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    get_user_avatar_partial,
    group_detail,
    group_detail_from_request,
    group_members,
    groups,
    search_group,
    search_user,
    user_activate,
    user_detail,
    user_detail_from_request,
    user_groups,
    user_pending_secrets,
    user_pending_secrets_csv,
    user_settings,
    users,
)

urlpatterns = (
    path(
        'login/',
        LoginView.as_view(template_name='accounts/login.html'),
        name='accounts.login',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='accounts/logout.html'),
        name='accounts.logout',
    ),
    path(
        'users/',
        users,
        name='accounts.user-list',
    ),
    path(
        'users/avatar/',
        get_user_avatar_partial,
        name='accounts.user.avatar',
    ),
    path(
        'users/detail/',
        user_detail_from_request,
        name='accounts.user-detail-from-request',
    ),
    path(
        'users/search/',
        search_user,
        name='accounts.search-user',
    ),
    path(
        'users/<str:username>/',
        user_detail,
        name='accounts.user-detail',
    ),
    path(
        'users/<str:username>/pending-secrets/',
        user_pending_secrets,
        name='accounts.user-pending-secrets',
    ),
    path(
        'users/<str:username>/pending-secrets/csv/',
        user_pending_secrets_csv,
        name='accounts.user-pending-secrets-csv',
    ),
    path(
        'users/<str:username>/reactivate',
        user_activate,
        name='accounts.user-reactivate',
    ),
    path(
        'users/<str:username>/deactivate',
        user_activate,
        {'deactivate': True},
        name='accounts.user-deactivate',
    ),
    path(
        'users/<str:username>/groups/',
        user_groups,
        name='accounts.user-groups',
    ),
    path(
        'groups/',
        groups,
        name='accounts.group-list',
    ),
    path(
        'groups/search/',
        search_group,
        name='accounts.search-group',
    ),
    path(
        'groups/detail/',
        group_detail_from_request,
        name='accounts.group-detail-from-request',
    ),
    path(
        'groups/<str:groupname>/members/',
        group_members,
        name='accounts.group-members',
    ),
    path(
        'groups/<str:groupname>/',
        group_detail,
        name='accounts.group-detail',
    ),
    path(
        'settings/',
        user_settings,
        name='accounts.user-settings',
    ),
)
