from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    url(
        r'^$',
        views.dashboard,
        name='dashboard',
    ),
    url(
        r'^access_requests/$',
        views.access_request_list,
        name='secrets.access_request-list',
    ),
    url(
        views.access_request_detail,
        r'^access_requests/(?P<pk>\d+)$',
        name='secrets.access_request-detail',
    ),
    url(
        r'^access_requests/(?P<pk>\d+)/(?P<action>(allow|deny))$',
        views.access_request_review,
        name='secrets.access_request-review',
    ),
    url(
        r'^secrets/$',
        views.secret_list,
        name='secrets.secret-list',
    ),
    url(
        views.secret_detail,
        r'^secrets/(?P<pk>\d+)$',
        name='secrets.secret-detail',
    ),
    url(
        r'^secrets/(?P<pk>\d+)/delete$',
        views.secret_delete,
        name='secrets.secret-delete',
    ),
    url(
        r'^secrets/(?P<pk>\d+)/download$',
        views.secret_download,
        name='secrets.secret-download',
    ),
    url(
        views.secret_edit,
        r'^secrets/(?P<pk>\d+)/edit$',
        name='secrets.secret-edit',
    ),
    url(
        r'^secrets/(?P<pk>\d+)/request_access$',
        views.access_request_create,
        name='secrets.secret-request_access',
    ),
    url(
        r'^secrets/(?P<pk>\d+)/share$',
        views.secret_share,
        name='secrets.secret-share',
    ),
    url(
        r'^secrets/add/(?P<content_type>\w+)$',
        views.secret_edit,
        name='secrets.secret-add',
    ),
    url(
        r'^secrets/search$',
        views.secret_search,
        name='secrets.secret-search',
    ),
)
