# Generated by Django 4.2.1 on 2023-06-11 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("secrets", "0028_sharedsecretdata_grant_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedsecretdata",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
