# Generated by Django 4.2.13 on 2024-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0033_secretrevision_encrypted_otp_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretrevision',
            name='encrypted_otp_key',
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='encrypted_otp_key_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
