# Generated by Django 4.2.13 on 2024-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0034_remove_secretrevision_encrypted_otp_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='encrypted_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
