# Generated by Django 5.2.1 on 2025-06-02 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secrets', '0035_remove_secretrevision_encrypted_otp_key_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='shared_groups',
            field=models.ManyToManyField(blank=True, through='secrets.SharedSecretData', through_fields=('secret', 'group'), to='auth.group'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='shared_users',
            field=models.ManyToManyField(blank=True, through='secrets.SharedSecretData', through_fields=('secret', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
