# Generated by Django 4.2.13 on 2024-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0035_secretrevision_encrypted_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='otp_key_set',
            field=models.BooleanField(default=False),
        ),
    ]
