# Generated by Django 5.2.1 on 2025-09-24 07:56

import django.db.models.deletion
import teamvault.apps.secrets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0037_change_secretrevision_plaintextdata_key_of_password_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecretChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashid', models.CharField(max_length=24, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=92)),
                ('description', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, validators=[teamvault.apps.secrets.models.validate_url])),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('access_policy', models.PositiveSmallIntegerField(choices=[(1, 'discoverable'), (2, 'everyone'), (3, 'hidden')])),
                ('needs_changing_on_leave', models.BooleanField(default=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'needs changing'), (3, 'deleted')], default=1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_changes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='secrets.secretchange')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='secrets.secretchange')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='secrets.secretrevision')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='secrets.secret')),
            ],
            options={
                'ordering': ('created',),
                'indexes': [models.Index(fields=['secret', 'created'], name='secretchange_secret_create_idx'), models.Index(fields=['actor', 'created'], name='secretchange_actor_create_idx'), models.Index(fields=['revision'], name='secretchange_revision_idx'), models.Index(fields=['parent'], name='secretchange_parent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('restored_from', models.F('id')), _negated=True), name='secretchange_no_self_restore'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='secretchange_no_self_parent')],
            },
        ),
    ]
