# Generated by Django 5.2.1 on 2025-07-07 11:30

import teamvault.apps.secrets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0037_change_secretrevision_plaintextdata_key_of_password_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='access_policy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'discoverable'), (2, 'everyone'), (3, 'hidden')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='name',
            field=models.CharField(default='', max_length=92),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='needs_changing_on_leave',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'needs changing'), (3, 'deleted')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[teamvault.apps.secrets.models.validate_url]),
        ),
        migrations.AddField(
            model_name='secretrevision',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
