# Generated by Django 5.2.1 on 2025-09-15 11:51

import django.db.models.deletion
import teamvault.apps.secrets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0037_change_secretrevision_plaintextdata_key_of_password_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecretMetaSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True, validators=[teamvault.apps.secrets.models.validate_url])),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('access_policy', models.PositiveSmallIntegerField(choices=[(1, 'discoverable'), (2, 'everyone'), (3, 'hidden')])),
                ('needs_changing_on_leave', models.BooleanField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'needs changing'), (3, 'deleted')])),
                ('meta_sha256', models.CharField(editable=False, max_length=64)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_snaps', to='secrets.secretrevision')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_meta_snaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'constraints': [models.UniqueConstraint(fields=('revision', 'meta_sha256'), name='uniq_meta_per_revision')],
            },
        ),
    ]
