# Generated by Django 5.2.1 on 2025-08-04 08:43

import django.db.models.deletion
import teamvault.apps.secrets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('secrets', '0038_secretrevision_last_read_secretmetasnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Further information on the secret.'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='secret',
            name='hashid',
            field=models.CharField(default='', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, validators=[teamvault.apps.secrets.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='secret',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='secretmetasnapshot',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='secretmetasnapshot',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='secretmetasnapshot',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, validators=[teamvault.apps.secrets.models.validate_url]),
        ),
        migrations.AlterField(
            model_name='secretmetasnapshot',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='secretrevision',
            name='hashid',
            field=models.CharField(default='', max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedsecretdata',
            name='grant_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sharedsecretdata',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='secret_share_data', to='auth.group'),
        ),
    ]
