# Generated by Django 5.2.1 on 2025-09-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0038_secretrevision_last_read_secretmetasnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='restored_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_children', to='secrets.secretrevision'),
        ),
    ]
