# Generated by Django 5.2.1 on 2025-09-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0039_secretrevision_last_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmetasnapshot',
            name='hashid',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
