# Generated by Django 5.2.1 on 2025-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0039_auto_20250707_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretrevision',
            name='last_read',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
