# Generated by Django 5.2.1 on 2025-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0040_secretmetasnapshot_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretmetasnapshot',
            name='name',
            field=models.CharField(default='unset', max_length=92),
            preserve_default=False,
        ),
    ]
