# Generated by Django 5.2.1 on 2025-09-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0041_secretmetasnapshot_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='secret_changes', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='changes', to='secrets.secretrevision')),
                ('secret', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='changes', to='secrets.secret')),
                ('snapshot', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='changes', to='secrets.secretmetasnapshot')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddIndex(
            model_name='secretchange',
            index=models.Index(fields=['secret', 'created'], name='secretchange_secret_create_idx'),
        ),
        migrations.AddField(
            model_name='secretchange',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='secrets.secretchange'),
        ),
        migrations.AddField(
            model_name='secretchange',
            name='restored_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='restores', to='secrets.secretchange'),
        ),
    ]

