# Generated by Django 6.0.5 on 2026-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0041_fix_passwords_old_payload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ('name', 'username', 'hashid')},
        ),
    ]
