# Generated by Django 5.2.1 on 2025-09-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0042_secretchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create through model for parents edges
        migrations.CreateModel(
            name='SecretChangeParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='+', to='secrets.secretchange')),
                ('parent', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='+', to='secrets.secretchange')),
            ],
        ),
        # Replace parents M2M to use the through model
        migrations.RemoveField(
            model_name='secretchange',
            name='parents',
        ),
        migrations.AddField(
            model_name='secretchange',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='secrets.SecretChangeParent', to='secrets.secretchange'),
        ),
        # Add extra indexes
        migrations.AddIndex(
            model_name='secretchange',
            index=models.Index(fields=['actor', 'created'], name='secretchange_actor_create_idx'),
        ),
        migrations.AddIndex(
            model_name='secretchange',
            index=models.Index(fields=['revision'], name='secretchange_revision_idx'),
        ),
        # Constraints
        migrations.AddConstraint(
            model_name='secretchange',
            constraint=models.CheckConstraint(check=models.Q(('restored_from', models.F('id')), _negated=True), name='secretchange_no_self_restore'),
        ),
        migrations.AddConstraint(
            model_name='secretchangeparent',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uniq_change_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='secretchangeparent',
            constraint=models.CheckConstraint(check=models.Q(('parent', models.F('child')), _negated=True), name='no_self_parent_edge'),
        ),
    ]

