# Generated by Django 5.2.1 on 2025-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0043_secretchange_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretchange',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='secrets.SecretChangeParent', to='secrets.secretchange'),
        ),
    ]

