# Generated by Django 5.2.1 on 2025-09-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0044_alter_secretchange_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretrevision',
            name='restored_from',
        ),
    ]

