# Generated by Django 5.2.1 on 2025-09-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0045_remove_secretrevision_restored_from'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecretMetaSnapshot',
            new_name='SecretMeta',
        ),
    ]

