# Generated by Django 5.2.1 on 2025-09-19 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0046_rename_secretmetasnapshot_to_secretmeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='secretchange',
            old_name='snapshot',
            new_name='metadata',
        ),
        migrations.AlterField(
            model_name='secretchange',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='secrets.SecretChangeParent', through_fields=('child', 'parent'), to='secrets.secretchange'),
        ),
        migrations.AlterField(
            model_name='secretmeta',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='secrets.secretrevision'),
        ),
        migrations.AlterField(
            model_name='secretmeta',
            name='set_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_metas', to=settings.AUTH_USER_MODEL),
        ),
    ]
