# Generated by Django 5.2.8 on 2026-01-07

from django.db import migrations


def change_user_contenttype(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(app_label='auth', model='user').first()
    if ct:
        ct.app_label = 'accounts'
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_custom_user_model'),
        ('contenttypes', '__latest__'),
    ]

    operations = [migrations.RunPython(change_user_contenttype, elidable=True)]
