# Generated by Django 4.2.5 on 2023-09-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_usertoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertoken",
            name="description",
        ),
        migrations.AddField(
            model_name="usertoken",
            name="label",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
