# Generated by Django 5.2.8 on 2026-01-08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_fix_user_contenttype"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
