# Generated by Django 6.0.2 on 2026-05-06 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
