# Generated by Django 6.0.5 on 2026-06-05 11:25

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. 'CI deploy key'", max_length=200
                    ),
                ),
                ("prefix", models.CharField(db_index=True, max_length=16, unique=True)),
                ("hashed_key", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prefix", "is_active"],
                        name="accounts_ap_prefix_5c5315_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "expires_at__lte",
                                models.ExpressionWrapper(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.functions.datetime.TruncDate(
                                            "created_at"
                                        ),
                                        "+",
                                        models.Value(datetime.timedelta(days=365)),
                                    ),
                                    output_field=models.DateField(),
                                ),
                            )
                        ),
                        name="api_token_expires_within_365d",
                    )
                ],
            },
        ),
    ]
